execute 'source' fnameescape(g:vimdir . '/vanilla.vim')
execute 'source' fnameescape(g:vimdir . '/mapping.vim')
execute 'source' fnameescape(g:vimdir . '/plugins.vim')
execute 'source' fnameescape(g:vimdir . '/setting.plugins.vim')
execute 'source' fnameescape(g:vimdir . '/mapping.plugins.vim')
execute 'source' fnameescape(g:vimdir . '/ui.plugins.vim')
execute 'source' fnameescape(g:vimdir . '/ui.vim')
